#!/usr/bin/env python3
"""Regenerate .phoenix-ide.env to route Phoenix at the GitHub Copilot API.

Phoenix's `openai_chat_completions` backend is wire-compatible with
`https://api.githubcopilot.com/chat/completions`, which accepts the GitHub
OAuth token that the Copilot CLI stores in `~/.copilot/config.json` directly
as a bearer credential.

Run this after a Copilot CLI re-login, which rotates that token.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

CONFIG = Path.home() / ".copilot" / "config.json"
ENV_FILE = Path(__file__).resolve().parent.parent / ".phoenix-ide.env"
CHAT_URL = "https://api.githubcopilot.com/chat/completions"

# Model set the raw OAuth token is entitled to. Verify with:
#   curl -H "Authorization: Bearer $TOKEN" \
#        -H "Copilot-Integration-Id: vscode-chat" \
#        https://api.githubcopilot.com/models
MODELS = [
    {
        "id": "copilot/gpt-4o",
        "api_name": "gpt-4o-2024-11-20",
        "backend": "openai_chat_completions",
        "family": "OpenAI",
        "description": "GPT-4o via GitHub Copilot (128K ctx, 16K out)",
        "context_window": 128000,
        "max_output_tokens": 16384,
        "recommended": True,
        "supports_tool_search": False,
    },
    {
        "id": "copilot/gpt-4o-mini",
        "api_name": "gpt-4o-mini",
        "backend": "openai_chat_completions",
        "family": "OpenAI",
        "description": "GPT-4o mini via GitHub Copilot (128K ctx, fast)",
        "context_window": 128000,
        "max_output_tokens": 4096,
        "recommended": False,
        "supports_tool_search": False,
    },
]


def read_token() -> str:
    if not CONFIG.exists():
        sys.exit(f"error: {CONFIG} not found — run `copilot` and sign in first")
    # config.json is JSONC: the Copilot CLI writes a leading comment banner.
    raw = re.sub(r"^\s*//.*$", "", CONFIG.read_text(), flags=re.M)
    tokens = json.loads(raw).get("copilotTokens") or {}
    if not tokens:
        sys.exit(f"error: no copilotTokens in {CONFIG} — sign in with `copilot` first")
    return next(iter(tokens.values()))


def main() -> None:
    token = read_token()
    body = f"""# Phoenix IDE local LLM config -- GitHub Copilot backend.
#
# Generated by scripts/phoenix-copilot-env.py. Gitignored: contains a credential.
# Token source: ~/.copilot/config.json -> copilotTokens
# Regenerate after a Copilot CLI re-login: ./scripts/phoenix-copilot-env.py

OPENAI_API_KEY={token}
OPENAI_CHAT_COMPLETIONS_BASE_URL={CHAT_URL}
LLM_AUTH_HEADER=bearer
LLM_CUSTOM_HEADERS=Copilot-Integration-Id: vscode-chat\\nEditor-Version: vscode/1.99.3
DEFAULT_MODEL=copilot/gpt-4o
PHOENIX_LLM_MODELS={json.dumps(MODELS, separators=(",", ":"))}
"""
    ENV_FILE.write_text(body)
    os.chmod(ENV_FILE, 0o600)
    print(f"wrote {ENV_FILE} (mode 600) with {len(MODELS)} Copilot models")
    print("restart Phoenix to pick it up: ./dev.py restart")


if __name__ == "__main__":
    main()
